### ISSUE TITLE
problem when reading from pipe

### ISSUE THREAD

**Issue by calvinckfong** [OpenVisualCloud/SVT-HEVC#373] opened 2019-09-27 02:12 UTC
Good day!  When I follow the instruction in readme to read from pipe, there is a problem in v1.4.0 or above.  I used the follow command and several bytes shifted are observed.  There is no such problem in v1.3.0.  Is there any extra option I needed?  Thanks!
 
`$FFMPEG -hide_banner -loglevel 0 -i $SRC -pix_fmt yuv420p - | $SVTHEVC -i stdin -w $WIDTH -h $HEIGHT -n $FRAME_NUM -b $OUT.hevc`

![svt-hevc-500](https://user-images.githubusercontent.com/16603747/65736816-f2c06e80-e10e-11e9-839a-7c3c1e2c96e9.png)

**Comment by Selur** [comment] 2019-09-28 17:42
Also y4m pipe doesn't work,
[code]ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\Test-AAC-5.1.mp4" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -encMode 8 -i stdin -fps-num 25 -fps-denom 1 -n 834 -profile 2  -b "E:\Temp\Test-AAC-5.1_new_19_36_40_7610_01.265"[/code]
fails until "-w ... -h ..." is added, so in case this should work: it doesn't.
(used: commit 3d68dd8397400bd70b48710f1b3b43a0bb3872f3)

Only way to get proper output files is atm. is not to use pipes.

**Comment by intelmark** [comment] 2019-09-30 14:00
@calvinckfong  Could you provide a command line without the variables so we can see the exact parameters ($WIDTH, $HEIGHT, $SRC etc.) as well as the input stream?
thanks..

**Comment by intelmark** [comment] 2019-09-30 14:04
@selur - Could you open a new issue on this problem (unless you strong believe it to be related the first issue)?

**Comment by Selur** [comment] 2019-09-30 14:18
Since I strongly believe that in general pipe input is broken and my problem is related to the first issue:

```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -fps-num 25 -bit-deph 10 -fps-denom 1 -n 429 -profile 2  -b "E:\Output\borked_y4m.265"
```
produces:
```
-------------------------------------------
SVT-HEVC Encoder
SVT [Error]: Instance 1: Invalid TileColumnCount. Maximum TileColumnCount for width 0 is 0
SVT [Error]: Instance 1: Invalid TileRowCount. Maximum TileRowCount for height 0 is 0
Error in configuration, could not begin encoding! ...
Run SvtHevcEncApp -help for a list of options
Encoder finished
```
no output.

```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -w 640 -h 480 -bit-deph 10 -fps-num 25 -fps-denom 1 -n 429 -profile 2  -b "E:\Output\borked_y4m.265"
```
produces:
```
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:  SVT-HEVC Encoder Lib v1.4.1
SVT [build]  :  GCC 9.2.0        64 bit
LIB Build date: Sep 23 2019 15:04:08
-------------------------------------------
Number of logical cores available: 48
Number of PPCS 54
-------------------------------------------
SVT [config]: Main10 Profile    Tier (auto)     Level (auto)
SVT [config]: EncoderMode / Tune                                        : 7 / 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat / EncoderColorFormat     : 10 / 0 / 1
SVT [config]: SourceWidth / SourceHeight                                        : 640 / 480
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 25 / 0
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 32 / 17 / 1
SVT [config]: BitRateReduction / ImproveSharpness                               : 0 / 0
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV    : 1 / 1 / 0 / 0
-------------------------------------------
Encoding       429
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         429            25.00 fps                  9448056              4404.69 kbps


Channel 1
Average Speed:          228.07 fps
Total Encoding Time:    1881 ms
Total Execution Time:   1972 ms
Average Latency:        236 ms
Max Latency:            334 ms
Encoder finished
```
output is broken

```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f rawvideo - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -w 640 -h 480 -bit-depth 10 -n 429 -profile 2  -b "E:\Output\borked_raw.265"
```

```
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:  SVT-HEVC Encoder Lib v1.4.1
SVT [build]  :  GCC 9.2.0        64 bit
LIB Build date: Sep 23 2019 15:04:08
-------------------------------------------
Number of logical cores available: 48
Number of PPCS 54
-------------------------------------------
SVT [config]: Main10 Profile    Tier (auto)     Level (auto)
SVT [config]: EncoderMode / Tune                                        : 7 / 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat / EncoderColorFormat     : 8 / 0 / 1
SVT [config]: SourceWidth / SourceHeight                                        : 640 / 480
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 25 / 0
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 32 / 17 / 1
SVT [config]: BitRateReduction / ImproveSharpness                               : 0 / 0
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV    : 1 / 1 / 0 / 0
-------------------------------------------
Encoding       429
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         429            25.00 fps                 20158572              9397.94 kbps


Channel 1
Average Speed:          237.02 fps
Total Encoding Time:    1810 ms
Total Execution Time:   1894 ms
Average Latency:        222 ms
Max Latency:            295 ms
Encoder finished
```

uploaded the input and the output files to:
https://drive.google.com/open?id=1mV-aGdiNSeEnWqx5R-c8XUPqqdpFpuFH

**Comment by intelmark** [comment] 2019-09-30 19:50
@Selur - I have a fix that should fix y4m piped input.  Would you be able to verify?

https://github.com/intelmark/SVT-HEVC/tree/stdin_y4m

**Comment by Selur** [comment] 2019-09-30 20:13
I'll give it a try (I use https://github.com/m-ab-s/media-autobuild_suite) for the compilation, but adjusting the url to the git should allow me to build the forked version.
I'll probably be able to test it and report back in an hour or so.

**Comment by Selur** [comment] 2019-09-30 20:45
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -fps-num 25 -bit-depth 10 -fps-denom 1 -n 429 -profile 2  -b "E:\Output\test_y4m.265"



I gave it a try and called:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -fps-num 25 -bit-depth 10 -fps-denom 1 -n 429 -profile 2  -b "E:\Output\test_y4m.265"
```
y4m was detected:
```
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:  SVT-HEVC Encoder Lib v1.4.0
SVT [build]  :  GCC 9.2.0        64 bit
LIB Build date: Sep 30 2019 22:38:45
-------------------------------------------
Number of logical cores available: 48
Number of PPCS 54
-------------------------------------------
SVT [config]: Main10 Profile    Tier (auto)     Level (auto)
SVT [config]: EncoderMode / Tune                                        : 7 / 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat / EncoderColorFormat     : 10 / 0 / 1
SVT [config]: SourceWidth / SourceHeight                                        : 640 / 352
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 25 / 1 / 25 / 0
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 3 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 32 / 17 / 1
SVT [config]: BitRateReduction / ImproveSharpness                               : 0 / 0
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV    : 1 / 1 / 0 / 0
-------------------------------------------
Encoding       429
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         429            25.00 fps                   139984              65.26 kbps


Channel 1
Average Speed:          299.79 fps
Total Encoding Time:    1431 ms
Total Execution Time:   1516 ms
Average Latency:        176 ms
Max Latency:            236 ms
Encoder finished
```
and the output looked fine.
(bad quality, but that is due to the settings and the really low average bit rate)

raw pipe is still broken, tried with:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f rawvideo - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -w 640 -h 480 -bit-depth 10 -n 429 -profile 2  -b "E:\Output\test_raw.265"
```
output is way different than before, but still broken.

So thanks for finding a fix to the y4m piping issue. :)

**Comment by Austin-Hu** [comment] 2019-10-03 23:08
Hi @Selur ,

For the broken bitstream via pipe issue, please try the command line below:

`ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f rawvideo - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -w 640 -h **352** -bit-depth 10 -n 429 -profile 2  -b "E:\Output\test_raw.265"`

With almost the same options except for yuv4mpegpipe, you got the correctly encoded bitstream no matter you set the "-w" and "-h" options or not, or even though you set incorrect values. Because according to Y4M [data format](https://wiki.multimedia.cx/index.php/YUV4MPEG2), we can get the parameters from its header, and they will replace the configurations of SvtHevcEncApp (in function read_y4m_header()) with correct values.

But when using pipe, we just got raw YUV data decoded by ffmpeg, and the incorrect "-h" option would set the height of the bitstream, and would induce incorrect YUV data reading offset for encoder. So we need set those options correctly for data transition via pipe.

Thanks!

**Comment by Austin-Hu** [comment] 2019-10-03 23:09
Hi @calvinckfong , could you also share your "$SRC" file with us (not sure you can also upload it [here](https://drive.google.com/drive/folders/1mV-aGdiNSeEnWqx5R-c8XUPqqdpFpuFH))? Thanks!

**Comment by Selur** [comment] 2019-10-04 04:56
@Austin-Hu: you are right, I messed up the height when using raw yuv.
-> so the fix from intelmark does fix the piping for me, for both y4m and raw input :)

**Comment by calvinckfong** [comment] 2019-10-04 05:04
> Hi @calvinckfong , could you also share your "$SRC" file with us (not sure you can also upload it [here](https://drive.google.com/drive/folders/1mV-aGdiNSeEnWqx5R-c8XUPqqdpFpuFH))? Thanks!

Hi @Austin-Hu 

My source file is created from ffmpeg with testsrc2 like the command below:
`ffmpeg -f lavfi -i testsrc2=d=3:s=1280x720 source.mp4`

For simplicity, you can pipe from ffmpeg to SvtHevcEncApp directly.

Thanks!

**Comment by Selur** [comment] 2019-10-04 05:20
Another pipe issue, that seems to be related (not sure whether I should better open a separate issue).
Unless I messed up somehow 8bit encoding via pipe seems to be broken
Using:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p -vsync 0  -f rawvideo - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -w 640 -h 352 -bit-depth 8 -n 429 -color-format 1 -profile 1  -b "E:\Output\test_raw.265"
```
(changed from yuv420p10le to yuv420p in the ffmpeg call and set bit-depth 8, color-format 1 and profile 1), I get broken output.

When using y4mpegpipe:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -n 429 -profile 1  -b "E:\Output\test_raw.265"
```
I get:
> SVT-HEVC Encoder
chroma format not supported
Error found when reading the y4m file parameters.
Error in configuration, could not begin encoding! ...
Run SvtHevcEncApp -h

=> Seems like either 8bit encoding isn't working for pipe input.

**Comment by Austin-Hu** [comment] 2019-10-07 15:55
Hi @Selur ,

Please help confirm that with PR #380 applied, either y4mpegpipe or rawvideo (pipe) can work, with yuv420p or yuv420p10le format. And the correct command line to generate yuv420p10le format should be;
`
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt **yuv420p10** -vsync 0 **-strict -1** -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -n 429 -profile 1  -b "E:\Output\test_raw.265"
`

Thanks!

**Comment by Austin-Hu** [comment] 2019-10-07 16:31
Hi @calvinckfong ,

At first, please add the "-f" option with either rawvideo or yuv4mpegpipe into your command line, otherwise the encoder would get null data YUV input:

```
$FFMPEG -hide_banner -loglevel 0 -i $SRC -pix_fmt yuv420p -f rawvideo - | $SVTHEVC -i stdin -w $WIDTH -h $HEIGHT -n $FRAME_NUM -b $OUT.hevc
```

We confirmed that with @intelmark 's PR #379 which has been merged, the "byte shifted" issue can be addressed. And we got the decoded output from the encoded bitstream:
![image](https://user-images.githubusercontent.com/51988754/66330357-12ad1a80-e8e5-11e9-8064-65d2623d1f20.png)

So please close this issue, after PR #380 is merged and your verification. Thanks!

**Comment by Selur** [comment] 2019-10-07 17:00
@Austin-Hu: having some issues with my build system here, can you share a windows build?

**Comment by 1480c1** [comment] 2019-10-07 17:02
@Selur, open the mintty terminal in mabs, run
```bash
source /build/media-suite_helper.sh
do_vcs "https://github.com/OpenVisualCloud/SVT-HEVC.git"
do_patch "https://patch-diff.githubusercontent.com/raw/OpenVisualCloud/SVT-HEVC/pull/380.patch" am
do_cmakeinstall video -DUNIX=OFF
```

and check

**Comment by 1480c1** [comment] 2019-10-07 17:08
[SvtHevcEncApp.zip](https://github.com/OpenVisualCloud/SVT-HEVC/files/3698626/SvtHevcEncApp.zip)

Here's a build

**Comment by Selur** [comment] 2019-10-07 17:09
@1480c1 : Thanks! (seeing your command line I found my typo :))
-----------
I tried:

1. raw pipe yuv420p:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p -vsync 0  -f rawvideo - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -w 640 -h 352 -bit-depth 8 -n 429 -color-format 1 -profile 1  -b "E:\Output\test_8bitraw.265"
```
-> worked, output is fine

2. y4m pipe yuv420p:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -n 429 -profile 1  -b "E:\Output\test_8bity4m.265
```
->  worked, output is fine

3. raw pipe yuv420p10le:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f rawvideo - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -w 640 -h 352 -bit-depth 10 -n 429 -color-format 1 -profile 1  -b "E:\Output\test_10bitraw.265"
```
->  worked, output is fine

4. y4m pipe yuv420p10le:
```
ffmpeg -y -loglevel fatal -noautorotate -nostdin -threads 8 -i "F:\TestClips&Co\files\test.avi" -map 0:0 -an -sn -vf zscale=rangein=tv:range=tv -pix_fmt yuv420p10le -strict -1 -vsync 0  -f yuv4mpegpipe - | SvtHevcEncApp -i stdin -fps-num 25 -fps-denom 1 -n 429 -profile 1  -b "E:\Output\test_10bity4m.265
```
->  worked, output is


Seems like the patch fixed the issue.

**Comment by Austin-Hu** [comment] 2019-10-07 17:12
Thanks for your detailed verification, @Selur ! We will go through the merging process for PR #380 .

**Closed** 2019-10-08 23:12 UTC
Labels: enhancement
