### ISSUE TITLE
[SVT-HEVC]The encoded streams have difference between AsmType enabled and disabled in encMode[0-2]

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-HEVC#272] opened 2019-07-23 09:19 UTC
[Test environment]
OS： Ubuntu 18.04.2 LTS
SVT CommitID: 94996f6

[Issue Description]
During run SVT-HEVC test with Commit ID 94996f6, found the encoded streams have difference between AsmType enabled and disabled in encMode[0-2].
The P420 and P422 input YUV have this issue, but P444 input YUV is blocked by "https://github.com/OpenVisualCloud/SVT-HEVC/issues/269"

Test command line we used:
encoders/SvtHevcEncApp -i yuvs/ParkJoy_864x480_10bit_50Hz_P422.yuv  -b asm_test_M0_ParkJoy_864x480_10bit_50Hz_P422_Q41_OQ_0.265    -w 864  -h 480  -bit-depth 10  -fps 50  -intra-period 47  -n 20  -encMode 0  -tune 1  -asm 0  -compressed-ten-bit-format 0  -q 41  -color-format 2  -rc 0 
encoders/SvtHevcEncApp -i yuvs/ParkJoy_864x480_10bit_50Hz_P422.yuv  -b asm_test_M0_ParkJoy_864x480_10bit_50Hz_P422_Q41_OQ_1.265    -w 864  -h 480  -bit-depth 10  -fps 50  -intra-period 47  -n 20  -encMode 0  -tune 1  -asm 1  -compressed-ten-bit-format 0  -q 41  -color-format 2  -rc 0

encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b asm_test_M2_Fallout4_1920x1080_8bit_60Hz_P420_Q35_OQ_0.265  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -encMode 2  -tune 1  -asm 0  -compressed-ten-bit-format 0  -q 35  -color-format 1  -rc 0
encoders/SvtHevcEncApp -i yuvs/Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b asm_test_M2_Fallout4_1920x1080_8bit_60Hz_P420_Q35_OQ_1.265  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -encMode 2  -tune 1  -asm 1  -compressed-ten-bit-format 0  -q 35  -color-format 1  -rc 0

**Comment by tianjunwork** [comment] 2019-07-24 00:25
@GuCaixuan Thx reporting the issue.

**Comment by tianjunwork** [comment] 2019-07-24 00:35
Hi @GuCaixuan, similar to #161, you find bitstream difference between -asm 0 and 1, only for encMode[0-2]?

**Comment by GuCaixuan** [comment] 2019-07-24 00:48
@tianjunwork , Yes, only for encMode[0-2].

**Comment by liweki** [comment] 2019-07-24 08:44
This issue is still reproducible with the latest check in 5107c84.

**Comment by Austin-Hu** [comment] 2019-07-25 08:09
Confirmed that Jing's PR#[278](https://github.com/OpenVisualCloud/SVT-HEVC/pull/278) fixed the r2r issue with asm disabled and encMode <= 2. So @GuCaixuan, please close it after your verification.

Originally the issue didn't happen with asm enabled, even though PictureCopy8Bit() got incorrect chromaAreaWidth/chromaAreaHeight arguments for Cr/Cb components, because the SSE implementations for PicCopyKernel_funcPtrArray don't handle with the input width/height arguments, but with stride instead.

**Closed** 2019-07-26 01:47 UTC
Labels: P2, bug
