### ISSUE TITLE
SVT-HEVC+ffmpeg  Segmentation fault on Intel Xeon(24 cores, 48 threads)

### ISSUE THREAD

**Issue by PengStrongLee** [OpenVisualCloud/SVT-HEVC#219] opened 2019-06-19 03:08 UTC
I am using SVT-HEVC + ffmpeg plugin.  I install all env in docker and encode complete without errors. But I got two bugs:
When I create 1 instance use "./ffmpeg -i input.mp4 -c:v libsvt_hevc -rc 1 -b:v 10M -tune 0 -preset 9 -y test.265" it complete without errors and got 185 fps.
When I create 10 instances simultaneously(that is to say execute this script “./ffmpeg -i input.mp4 -c:v libsvt_hevc -rc 1 -b:v 10M -tune 0 -preset 9 -y test.265” 10 times simultaneously) all things run correctly. And we got 40 fps per instance.
But when I increase the instances to 20 or 30, it look running in terminal and got fps 118 or 160
First, this is strange, In principle, the number of instance is inversely proportional to FPS;
Second, I got core files after the process ended. I use gdb to debug the core files and got this message:
**Core was generated by `./ffmpeg -i demo_video/chiji_hevc_720p_8m_30fps_6min.mp4 -c:v libsvt_hevc -rc 1'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f7378e97216 in ?? ()
"/home/aiyu/ffmpeg/core.443927" is a core file.** 
 Third, when the instances number is 20 or more, that is, the program is still running while memory errors occur(which will generate the core files), whatever shell commands I exec in another terminal, errors appears like this:
**[root@xxx]# ls
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes**
It is strange. It looks like SVT creates so many processes that it reaches the system ceiling(I guess~) 
So

**Comment by tianjunwork** [comment] 2019-06-19 22:53
Hi @jsunintel Could you take a look at the seg fault?
@PengStrongLee for the third one, your guess is right. Please use -lp and -ss to limit the resource to each encoder instance if you run multiple ones. But if you still keep increasing the number of instance, you will still reach the limit.
@jsunintel is -lp and -ss exposed to ffmpeg?

**Comment by PengStrongLee** [comment] 2019-06-20 03:14
But here come a strange phenomena. When I run 1 instance on my machine, use the "htop", look like this:
<img width="218" alt="svt_lp48_ss_0_instance_1_cpu_usage" src="https://user-images.githubusercontent.com/24222433/59815802-5850d200-934c-11e9-8605-38a4e101f80e.PNG">

and when I run 10 instances(complete without error),  use "htop", it look like this:
<img width="225" alt="svt_lp_48_ss_0_cpu_usage_half" src="https://user-images.githubusercontent.com/24222433/59815820-669eee00-934c-11e9-863c-d819bac4b65d.PNG">

It is strange.It seems that the increase in the number of instances is rather the decline in cpu utilization. Generally, when 1 instance running the cpu is not used full, increasing instance should improve cpu utilization. But it is opposite.
Thanks.

**Comment by tianjunwork** [comment] 2019-06-20 04:10
@PengStrongLee what command you use monitored by htop?

**Comment by PengStrongLee** [comment] 2019-06-20 05:08
> INSTANCES=$2
> for((NUM=0;NUM<$INSTANCES;NUM++))
> do
>     sudo sysctl -w kernel.sched_rt_runtime_us=1000000
>     Bin/Release/SvtHevcEncApp -i $test_video -w 720 -h 1280 -lp 48 -ss 0 -o $output.hevc & export PID=$! sudo chrt -f -a -p 99 $PID &
> 
> done 

This is part of my test script. The for loop is used to run multi instances.

**Comment by jsunintel** [comment] 2019-06-20 05:20
@PengStrongLee your script showed you were running SvtHevcEncApp, but the description of this issue said it was about FFmpeg SVT HEVC plugin. Do you have seg fault in both cases?

**Comment by tianjunwork** [comment] 2019-06-20 05:24
> > INSTANCES=$2
> > for((NUM=0;NUM<$INSTANCES;NUM++))
> > do
> > sudo sysctl -w kernel.sched_rt_runtime_us=1000000
> > Bin/Release/SvtHevcEncApp -i $test_video -w 720 -h 1280 -lp 48 -ss 0 -o $output.hevc & export PID=$! sudo chrt -f -a -p 99 $PID &
> > done
> 
> This is part of my test script. The for loop is used to run multi instances.

Thx, I will take a look.

**Comment by tianjunwork** [comment] 2019-06-20 22:55
@PengStrongLee 
```
#!/bin/bash

INSTANCES=$1
for((NUM=0;NUM<$INSTANCES;NUM++))
do
    sudo sysctl -w kernel.sched_rt_runtime_us=1000000
    ./SvtHevcEncApp -i /home/vcse/jun/yuv/1920x1080.yuv -w 1920 -h 1080 -n 500 -ss 0 -b test_$NUM.hevc & export PID=$! sudo chrt -f -a -p 99 $PID &
done
```

**Comment by PengStrongLee** [comment] 2019-06-21 14:46
@tianjunwork I will try on my server next week. Thank you for your help

**Comment by fangtaoa** [comment] 2019-06-24 09:20
@tianjunwork  @PengStrongLee   I and PengStrongLee  are colleagues. We do tests on 8170 CPU. Before the fork error occurred in the docker environment. Now we are testing on the physical machine. There is no fork error.But, With the increase of instance, the utilization rate of CPU is very high at the beginning, but it becomes very low after about half a minute.

**Comment by tianjunwork** [comment] 2019-06-24 21:18
@fangtaoa Thanks for the info. I will let it run for a while to observe the cpu utilization drop.

**Comment by tianjunwork** [comment] 2019-06-25 00:20
@fangtaoa I run above https://github.com/OpenVisualCloud/SVT-HEVC/issues/219#issuecomment-504227955 script with 5 encoder instance on Xeon 6140 for 3 mins. The cpu utilization is always 100%. It seems like something special for Xeon 81xx including issue @221.

**Comment by PengStrongLee** [comment] 2019-06-25 02:26
@tianjunwork  Thanks for your help. I have run the SVT on physical machine without cpu utilization drop problem whatever instances running in the same time. But when I do the same thing in Docker, when I increase the instance number to 30:
"
when the instances number is 20 or more, that is, the program is still running without any errors, but whatever shell commands I exec in another terminal, errors appears like this:
[root@xxx]# ls
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes
bash: fork: retry: No child processes
"
this problem still comes out. And I can't enter the container bash while the fork error appears.
But there is no problems on the physical machine.  Do you have any opinions on running in Docker env? Thanks a lot.

**Comment by 1480c1** [comment] 2019-06-25 02:31
check ulimit? Might be low for docker containers

**Comment by PengStrongLee** [comment] 2019-06-25 06:36
@1480c1 
I have checked my /usr/lib/systemd/system/docker.service file, 
"
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
"
Is the LimitNPROC is not enough?

**Comment by PengStrongLee** [comment] 2019-06-25 07:09
@tianjunwork @1480c1  Have you tried running 30 SVT instances in docker env? 
(The same command running on physical machine without problems.)

**Comment by 1480c1** [comment] 2019-06-25 07:12
I've done docker with svt-av1, but not svt-hevc

**Comment by 1480c1** [comment] 2019-06-25 07:12
I'll see if I can help find out why when I wake up

**Comment by tianjunwork** [comment] 2019-06-27 19:18
@fangtaoa I can only reproduce the low cpu utilization when the memory usage goes to extreme.
With 3 instances of 8k encoding with -lad set to max, mem is almost all occupied.
Please check your memory usage when you see low cpu utilization.
![image](https://user-images.githubusercontent.com/4551215/60293923-205e0780-98d5-11e9-9331-69a5bc9d6514.png)

**Comment by fangtaoa** [comment] 2019-06-28 01:14
@tianjunwork OK. I'll try. Thanks!

**Comment by PengStrongLee** [comment] 2019-07-01 05:31
@tianjunwork  Have you tried run 20 or more SVT instances in docker?
We have change the param "-o" to "-b" for the output_file , this help us to solve the CPU utilization drop issue. Thanks a lot~. We run 20 or more SVT instances in physical machine  without any issue.
But the process fork error appeared just like I have mentioned above. Although the SVT still running but it seems wrong because the fps is extremely high(for example, 20 instances the fps is more than 120, 30 instance is more than 160 fps)
Could please help us to check the docker issue?
thanks a lot

**Comment by tianjunwork** [comment] 2019-07-09 17:32
This seems more like a docker issue, not SVT. My folks of Dockerfiles maintainer is debugging.

**Comment by liz-lawrens** [comment] 2019-07-09 23:53
@PengStrongLee I tried to replicate the issue #219 on our svt docker image and am unable to replicate it. I used your script and it runs fine for instances > 20. I ran it for 30 instances and average speed came to around ~9-10 fps. The script executes successfully and I don’t encounter any errors either. Could you please provide more info on the fork error that you are encountering as we are unable to replicate it on our docker images?

**Comment by liz-lawrens** [comment] 2019-07-12 17:49
@PengStrongLee As we discussed this doesn't seem to be an issue due to anything specific to this docker image.  Can we go ahead and close this?

**Comment by tianjunwork** [comment] 2019-07-16 16:53
@PengStrongLee any other issues you would like to follow up with us?

**Closed** 2019-07-19 16:31 UTC
Labels: discussion
