### ISSUE TITLE
Tile Support

### ISSUE THREAD

**Issue by shalin186** [OpenVisualCloud/SVT-HEVC#483] opened 2020-02-28 01:12 UTC
Hi,

I see that SVT-HEVC supports tiling for HEVC. Does it encode multiple tiles in parallel? When I try encoding using one tile vs multiple tiles I don't see any improvement in performance. Is there any plans to support encoding multiple tiles in parallel to improve the performance?

Shalin

**Comment by tianjunwork** [comment] 2020-02-28 23:02
Hi @shalin186, thank you for your question. Yes, it does. Tiles are processed in parallel.
Could you share your command line and master/tag?
I tested briefly on master. CPU usage does increase but not perf. It may be a regression. We will look into it.

**Comment by lijing0010** [comment] 2020-02-29 00:26
SVT is already highly parallelized, even without tiling. 
We had picture level, block level parallelism, so enabling tiling will not help you too much on fps.
But should be able to help to reduce the latency

**Comment by shalin186** [comment] 2020-03-05 00:56
@tianjunwork @lijing0010 
yes I agree that it is already highly parallelized. For higher quality presets the CPU utilization is pretty good, about 80%. But when I use preset 12, I see that CPU is under-utilized. I am executing this on a 96 core cloud instance. and I see CPU utilization to be around 5600 (60%). In this type of case, I would think that parallel tile encoding would help. But in my case, I see no difference in performance with 1 tile vs 16 tiles. Here's my command line for your reference.

ffmpeg -stream_loop -1 -i test.mp4 -c:v libsvt_hevc  -rc 1  -preset 12 -f null -

the input is 8K (7680x3840) resolution. I made couple of changes in libsvt_hevc.c to enable the multiple tiles. basically I am just setting
param->tileColumnCount = 4;
param->tileRowCount = 4;

Let me know your thoughts on this.

Shalin

**Comment by tianjunwork** [comment] 2020-03-05 01:07
Hi @shalin186 thanks for the background.

**Comment by shalin186** [comment] 2020-03-09 22:26
Hi, 

just wanted to check if you are going to look into what I reported. And if my expectations that higher number of tiles should help the performance in preset 12 is valid?

Shalin

**Comment by tianjunwork** [comment] 2020-03-09 23:40
Hi @shalin186 , we are looking into it now and trying to find the regression.
With 8k(huge data) and preset 12(fast encoding), the bottleneck is memory bandwidth. CPU is starving for data. Using tiling won't improve CPU utilization much(or at all) at preset 12.
To see the difference of CPU utilization at preset 12, you can use `-nb` which read frames into buffer before encoding. Note, `-nb` is only used for testing.

**Comment by shalin186** [comment] 2020-03-10 17:36
Thanks for the explanation. As shown in my command line (ffmpeg -stream_loop -1 -i test.mp4 -c:v libsvt_hevc -rc 1 -preset 12 -f null - ), I am using ffmpeg for transcoding.  I don't see a way to use -nb option. Also, would such an option even help while using ffmpeg, as I am assuming that decoded frames from ffmpeg would be in main memory. So there's not much disk access going on.

**Comment by tianjunwork** [comment] 2020-03-10 21:53
yeah, `-nb` is only for testing purpose of svt sample app, not for any other integrated application. If you would like to see the difference of using -nb, you need to use the sample app.
Anyway, with 8k -perset 12, using tiling won't help much.

**Comment by shalin186** [comment] 2020-03-10 22:41
ok I will try out -nb option in standalone app. 
Can you also tell me in which case will I see the benefit of using multiple tiles?

**Comment by tianjunwork** [comment] 2020-03-11 00:18
Generally speaking, when CPU is not starving for data to process, e.g. encMode 0/1/2(since computation is heavy). And of cause, CPU usage is not full, there is still room to scale.

**Comment by tianjunwork** [comment] 2020-03-13 05:08
Hi @shalin186 , e.g. with `-hierarchical-levels 0` which means flat structure, no frame level parallelism, tile based encoding can greatly improve performance.
If all existing parallelism are enabled, tile based encoding won't improve much.
I confirmed there is no regression of tile base encoding on master.

70% improvement of fps.
```
$ ./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.yuv -w 1920 -h 1080  -n 2000 -encMode 5 -hierarchical-levels 0 -base-layer-switch-mode 1
Channel 1
Average Speed:          56.05 fps
Total Encoding Time:    35682 ms
Total Execution Time:   36172 ms
Average Latency:        2081 ms
Max Latency:            3339 ms

$ ./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.yuv -w 1920 -h 1080  -n 2000 -encMode 5 -hierarchical-levels 0 -base-layer-switch-mode 1 -tile_row_cnt 8 -tile_col_cnt 1
Channel 1
Average Speed:          96.68 fps
Total Encoding Time:    20687 ms
Total Execution Time:   21191 ms
Average Latency:        1216 ms
Max Latency:            1747 ms
```

5-6% improvement of fps.
```
 ./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.yuv -w 1920 -h 1080  -n 5000 -encMode 5
Channel 1
Average Speed:          184.22 fps
Total Encoding Time:    27141 ms
Total Execution Time:   27721 ms
Average Latency:        644 ms
Max Latency:            928 ms

$./SvtHevcEncApp -i ../../../../yuv/bbb_1920x1080_420p.yuv -w 1920 -h 1080  -n 5000 -encMode 5 -tile_row_cnt 8 -tile_col_cnt 1
Channel 1
Average Speed:          195.96 fps
Total Encoding Time:    25515 ms
Total Execution Time:   26116 ms
Average Latency:        606 ms
Max Latency:            901 ms
```

**Comment by tianjunwork** [comment] 2020-03-16 17:15
Hi @shalin186 , do you have any other questions to discuss? If not, could you close this issue?

**Closed** 2020-03-19 16:38 UTC
Labels: discussion
