### ISSUE TITLE
Some YUV422 source was encoded wrong with red block artifacts.

### ISSUE THREAD

**Issue by jsunintel** [OpenVisualCloud/SVT-HEVC#238] opened 2019-07-04 08:33 UTC
Reproducing steps:
1. Download 3dat_backup_20190702100830.yuv (3200x2400 uyvy422) from https://drive.google.com/drive/folders/1xZq6GT7fnwrEqPDOxgcqvhFfAIbvzcAr?usp=sharing.
2. Convert it to the format yuv422p, which is supported by SvtHevcEncApp, by "ffmpeg -r 30 -video_size 3200x2400 -f rawvideo -pixel_format uyvy422 -i 3dat_backup_20190702100830.yuv -f rawvideo -pix_fmt yuv422p 3dat.yuv"
3. Encode it by SVT: "./SvtHevcEncApp -i /work/clips/3dat.yuv -w 3200 -h 2400 -rc 1 -b /work/svt.mp4 -color-format 2"
4. Check the coded svt.mp4, which will show red block artifacts.

**Comment by jsunintel** [comment] 2019-07-04 08:34
The source 3dat.yuv contains no such red block artifacts, and if we encode it by x265, no such either. The artifacts are shown in the attached picture.

**Comment by kelvinhu325** [comment] 2019-07-08 03:05
to update status, root caused pink artifacts are  caused by SVT SAO from first I frame, pink artifacts appear if disabling SAO in cmdline by -sao 0, needs more debugging.

**Comment by kelvinhu325** [comment] 2019-07-09 01:12
This issue is fixed by PR https://github.com/OpenVisualCloud/SVT-HEVC/pull/242

**Comment by kelvinhu325** [comment] 2019-07-09 05:26
The PR #242 is merged to master, we may close this issue, thanks!

**Closed** 2019-07-09 18:00 UTC
Labels: bug
