### ISSUE TITLE
[SVT-HEVC]Some test found the bitstream size of encoded stream is differ between AsmType enable and disable for 8K resolution.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-HEVC#282] opened 2019-07-26 06:03 UTC
[Test environment]
OS： Ubuntu 18.04.2 LTS
SVT CommitID: 1a9474a

[Issue Description]
During run SVT-HEVC test with Commit ID 1a9474a, found the bitstream size of encoded stream is differ between AsmType enable and disable for 8K resolution.

Test command line we used:
encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/8k2D_musician_7680x3840_8bit_30Hz_P444.yuv  -b asm_test_M8_8k2D_musician_7680x3840_8bit_30Hz_P444_Q42_OQ_0.265  -w 7680  -h 3840  -bit-depth 8  -fps 30  -intra-period 23  -n 20  -encMode 8  -tune 1  -asm 0  -compressed-ten-bit-format 0  -q 42  -color-format 3  -rc 0
encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/8k2D_musician_7680x3840_8bit_30Hz_P444.yuv  -b asm_test_M8_8k2D_musician_7680x3840_8bit_30Hz_P444_Q42_OQ_1.265 -w 7680  -h 3840  -bit-depth 8  -fps 30  -intra-period 23  -n 20  -encMode 8  -tune 1  -asm 1  -compressed-ten-bit-format 0  -q 42  -color-format 3  -rc 0

encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/8k2D_musician_7680x3840_8bit_30Hz_P420.yuv  -b asm_test_M10_8k2D_musician_7680x3840_8bit_30Hz_P420_Q33_OQ_0.265 -w 7680  -h 3840  -bit-depth 8  -fps 30  -intra-period 23  -n 20  -encMode 10  -tune 1  -asm 0  -compressed-ten-bit-format 0  -q 33  -color-format 1  -rc 0 
encoders/SvtHevcEncApp -i /home/media/yuvs/SVT/yuvs/8k2D_musician_7680x3840_8bit_30Hz_P420.yuv  -b asm_test_M10_8k2D_musician_7680x3840_8bit_30Hz_P420_Q33_OQ_1.265 -w 7680  -h 3840  -bit-depth 8  -fps 30  -intra-period 23  -n 20  -encMode 10  -tune 1  -asm 1  -compressed-ten-bit-format 0  -q 33  -color-format 1  -rc 0 
![8K](https://user-images.githubusercontent.com/45022980/61929593-f9672400-afad-11e9-8069-85a112c511b2.PNG)

**Comment by Austin-Hu** [comment] 2019-07-31 05:08
It's a duplicated issue with Issue #[281](https://github.com/OpenVisualCloud/SVT-HEVC/issues/281) which has the same root cause, and it can be fixed by PR #[292](https://github.com/OpenVisualCloud/SVT-HEVC/pull/292) as well, with the 2 reported cases verified.

**Closed** 2019-08-02 20:21 UTC
Labels: bug, duplicate
