### ISSUE TITLE
While encoding P422 1080p/720p yuv files in OQ mode, the encoded SVT-HEVC clips has difference between buffered preload parameter (-nb) enabled and disabled

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-HEVC#160] opened 2019-03-26 03:54 UTC
Take 1080p/720p YUV P422 file as input,  and use application SvtHevcEncApp to do SVT-HEVC encode with buffered preload parameter (-nb) enabled and disabled, the generated two SVT-HEVC clips has difference in OQ mode (SQ & VMAF not found this issue).

YUV clips we used for the test:
Fallout4_1920x1080_8bit_60Hz_P422.yuv
DucksTakeOff_1280x720_8bit_50Hz_P422.yuv

List a pair command line as example:
- encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b bitstreams/buffered_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q30_OQ_40.265  -errlog bitstreams/buffered_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q30_OQ_40.errlog  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  **-n 40  -nb 40**  -color-format 2  -compressed-ten-bit-format 0  -encMode 1  -q 30  -rc 0  -tbr 1782880  -tune 1
- encoders/SvtHevcEncApp -i yuvs/DucksTakeOff_1280x720_8bit_50Hz_P422.yuv  -b bitstreams/buffered_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q30_OQ_-1.265  -errlog bitstreams/buffered_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q30_OQ_-1.errlog  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  **-n 40  -nb -1**  -color-format 2  -compressed-ten-bit-format 0  -encMode 1  -q 30  -rc 0  -tbr 1782880  -tune 1

md5 of two generated SVT-HEVC clips:
buffered_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q30_OQ_-1.265: e5828ec0a8dd4df1cd0b84f7e50528da
buffered_test_M1_DucksTakeOff_1280x720_8bit_50Hz_P422_Q30_OQ_40.265: 24d211095347c0ef8a4874507502ee2d

**Comment by tianjunwork** [comment] 2019-03-26 22:59
Hi @liweki Could you also check the bitstream simply by a binary viewer app like #161?

**Comment by liweki** [comment] 2019-03-27 08:47
Hi, @tianjunwork,
Also check the two bitstreams with HxD and Beyond Compare, the difference begins from offset 0011010. Please help double check, thanks.
![bitstreams_compare](https://user-images.githubusercontent.com/46477459/55061962-f3b90a80-50af-11e9-9b06-75f696aee0a4.png)

**Comment by lijing0010** [comment] 2019-03-28 06:49
-n 40 -nb 40 means cache 40 frames in buffer and process 40 frames
-n 40 -nb 1 means use the 1st frame 40 times
-n 40 -nb 20 means encode total 40 frame, which consists frame 0,1,2...19,0,1,2...19
so they are different. In the latter case you'll get 40 frames: 1 intra frame and 39 skip frame.
This is usually for testing.

**Comment by lijing0010** [comment] 2019-04-02 07:55
-nb -1, not -nb 1

**Comment by intelmark** [comment] 2019-06-21 16:06
Was able to confirm this issue still exists with the current repo:

c:\repos\SVT-HEVCcurrent\Bin\Debug\SvtHevcEncApp -i DucksTakesOff_1280x720_50Hz_P422.yuv -b DucksTakesOff_1280x720_50Hz_P422_Q30_0Q_40.265 -errlog DucksTakesOff_1280x720_50Hz_P422_Q30_0Q_40.errlog -w 1280 -h 720 -bit-depth 8 -fps 50 -intra-period 47 -n 40 -nb 40 -color-format 2 -compressed-ten-bit-format 0 -encMode 1 -q 30 -rc 0 -tbr 182880 -tune 1


c:\repos\SVT-HEVCcurrent\Bin\Debug\SvtHevcEncApp -i DucksTakesOff_1280x720_50Hz_P422.yuv -b DucksTakesOff_1280x720_50Hz_P422_Q30_0Q_-1.265 -errlog DucksTakesOff_1280x720_50Hz_P422_Q30_0Q_40.errlog -w 1280 -h 720 -bit-depth 8 -fps 50 -intra-period 47 -n 40 -nb -1 -color-format 2 -compressed-ten-bit-format 0 -encMode 1 -q 30 -rc 0 -tbr 182880 -tune 1

c:\testfiles>FCIV DucksTakesOff_1280x720_50Hz_P422_Q30_0Q_-1.265
//
// File Checksum Integrity Verifier version 2.05.
//
f1925705ecdfa7c76f5c20afaab5b3fb duckstakesoff_1280x720_50hz_p422_q30_0q_-1.265

c:\testfiles>FCIV DucksTakesOff_1280x720_50Hz_P422_Q30_0Q_40.265
//
// File Checksum Integrity Verifier version 2.05.
//
c6766257d66ec901f90cdf89a68f8427 duckstakesoff_1280x720_50hz_p422_q30_0q_40.265

<img width="1182" alt="compare" src="https://user-images.githubusercontent.com/50715202/59935993-d7551180-9403-11e9-8ea9-91e9519299bb.png">

**Comment by Austin-Hu** [comment] 2019-06-27 08:38
Issue tracing status:
1. This is a random issue that we would get different MD5 for the encoded clip, with the same SvtHevcEncApp command line (configuration). So it means that it's not related to the "-nb" buffered preload parameter.
2. The issue can be also reproduced by encoding only 1 (the 1st key) frame, by setting "-n" with 1.
3. The issue can be also reproduced with YUV 420 or 444 format, but with lower probability.
4. After comparing the binaries of the encoded clips, the difference starts at the Cr component of CU (1216, 192). And found that its Cr EO (Edge Offset) values were different, so that with the same Cr values feeding into the SAO filter, the output Cr ones were different:
![Cr_EO_diff](https://user-images.githubusercontent.com/51988754/60248981-5bbcfe00-98f6-11e9-83cd-7d4cfcd44c74.png)
5. The issue occurs for Tune 1 only, as SAO is turned on by default. Also tried to turn on SAO for either Tune 0 or 2, the issue also happened. So the random issue happens with SAO filter enabled.
6. The Cr EO values are determined by some specific (the Cr buffer offset as the input argument of SaoGatherFunctionTableLossy, plus the pixel offset, e.g. the pixel in row 60 and column 24) bufferCr region of the reconstruction picture, when SaoGatherFunctionTableLossy is invoked for Cr component.
7. The specific bufferCr region can be updated during intra-prediction, reconstruction generation or de-blocking when processing some CUs, for example, it will be updated when de-blocking for CU (1088, 256).  And tracked that when processing the CU (1216, 192), it would randomly be done ahead of CU (1088, 256), so that the specific bufferCr region hadn't been updated yet, and would cause the different Cr EO values later.

So will continue tracing the issue, and need to check whether it's a regression by some previous commit.

**Comment by intelmark** [comment] 2019-07-02 16:35
I've been able to duplicate this though in a different CU using:
-i C:/testfiles/DucksTakesOff_1280x720_50Hz_P422.yuv -b c:/testfiles/DucksTakesOff_1280x720_50Hz_P422_Q30_0Q_2.265  -w 1280 -h 720 -bit-depth 8 -fps 50 -intra-period 47 -n 1 -color-format 2 -compressed-ten-bit-format 0 -encMode 1 -q 30 -rc 0 -tbr 182880 -tune 1



![image](https://user-images.githubusercontent.com/50715202/60529934-90d99f80-9cac-11e9-806b-fbc81a9559b8.png)

**Comment by kelvinhu325** [comment] 2019-07-09 01:10
my change for fixing issue #238 in PR https://github.com/OpenVisualCloud/SVT-HEVC/pull/242 also fixed this issue as @austin-Hu

**Comment by lijing0010** [comment] 2019-07-09 03:08
> Issue tracing status:
> 
> 1. This is a random issue that we would get different MD5 for the encoded clip, with the same SvtHevcEncApp command line (configuration). So it means that it's not related to the "-nb" buffered preload parameter.
> 2. The issue can be also reproduced by encoding only 1 (the 1st key) frame, by setting "-n" with 1.
> 3. The issue can be also reproduced with YUV 420 or 444 format, but with lower probability.
> 4. After comparing the binaries of the encoded clips, the difference starts at the Cr component of CU (1216, 192). And found that its Cr EO (Edge Offset) values were different, so that with the same Cr values feeding into the SAO filter, the output Cr ones were different:
>    ![Cr_EO_diff](https://user-images.githubusercontent.com/51988754/60248981-5bbcfe00-98f6-11e9-83cd-7d4cfcd44c74.png)
> 5. The issue occurs for Tune 1 only, as SAO is turned on by default. Also tried to turn on SAO for either Tune 0 or 2, the issue also happened. So the random issue happens with SAO filter enabled.
> 6. The Cr EO values are determined by some specific (the Cr buffer offset as the input argument of SaoGatherFunctionTableLossy, plus the pixel offset, e.g. the pixel in row 60 and column 24) bufferCr region of the reconstruction picture, when SaoGatherFunctionTableLossy is invoked for Cr component.
> 7. The specific bufferCr region can be updated during intra-prediction, reconstruction generation or de-blocking when processing some CUs, for example, it will be updated when de-blocking for CU (1088, 256).  And tracked that when processing the CU (1216, 192), it would randomly be done ahead of CU (1088, 256), so that the specific bufferCr region hadn't been updated yet, and would cause the different Cr EO values later.
> 
> So will continue tracing the issue, and need to check whether it's a regression by some previous commit.

Hi Austin, please double check for 420 and 444

**Comment by Austin-Hu** [comment] 2019-07-09 04:28
Confirmed that I made a mistake in Item 3 of my last comment, due to the incorrect repeat MD5 values fetching during my testing... This issue didn't happen with YUV 420 or 444.

So @liweki , please also verify the issue in your side as PR #[242](https://github.com/OpenVisualCloud/SVT-HEVC/pull/242) has been merged.

**Closed** 2019-07-10 19:09 UTC
Labels: P2, bug
