### ISSUE TITLE
EbH265EncStreamHeader issue

### ISSUE THREAD

**Issue by rexvl** [OpenVisualCloud/SVT-HEVC#392] opened 2019-10-11 04:55 UTC
There is no proper way to release the buffer allocated in EbH265EncStreamHeader. EbH265EncStreamHeader leaves wrapperPtr field uninitialized so we got the exception on EbH265ReleaseOutBuffer call(on windows) or memory leak(on linux).

**Comment by tianjunwork** [comment] 2019-10-11 19:20
Hi @rexvl, could you let me know how you use SVT APIs to trigger exception, so that once I fixed the issue I can confirm on my side.

**Comment by rexvl** [comment] 2019-10-14 00:17
Hi @tianjunwork, sorry for the delay. You can add debug calls of  EbH265EncStreamHeader/EbH265ReleaseOutBuffer into EbAppContext.c just aftet EbInitEncoder call. 

Please see attache patch for details. Then you should start Debug version of SvtHevcEncApp.exe to encode anywhere and you got the crash on EbH265ReleaseOutBuffer call after EbH265EncStreamHeader.  

On Release build we so no issue due to uninited wrapperPtr is zeroed but we got the memory leak. 

[EbH265EncStreamHeader.zip](https://github.com/OpenVisualCloud/SVT-HEVC/files/3722643/EbH265EncStreamHeader.zip)

**Comment by tianjunwork** [comment] 2019-10-14 03:45
Hi @rexvl, thank you for the detailed information. We will work on it.

**Comment by intelmark** [comment] 2019-10-14 17:44
@revxl - We seem to be having troubles downloading the patch file (it seems to be 0 bytes).  Can you recheck on your end and perhaps try again or suggest an alternative location?

thanks!

**Comment by rexvl** [comment] 2019-10-15 00:43
Hi @intelmark, I reuploaded the file

[EbH265EncStreamHeader.zip](https://github.com/OpenVisualCloud/SVT-HEVC/files/3726910/EbH265EncStreamHeader.zip)

**Comment by jsunintel** [comment] 2019-10-15 08:37
The buffers allocated in EbH265EncStreamHeader don't need the manual free op, for they are allocated by EB_MALLOC, which tracks the allocation. Those mem will get freed automatically when closing.

#define EB_MALLOC(type, pointer, nElements, pointerClass) \
    pointer = (type) malloc(nElements); \
    if (pointer == (type)EB_NULL) { \
        return EB_ErrorInsufficientResources; \
	    } \
	    else { \
        memoryMap[*(memoryMapIndex)].ptrType = pointerClass; \
        memoryMap[(*(memoryMapIndex))++].ptr = pointer; \
		if (nElements % 8 == 0) { \
			*totalLibMemory += (nElements); \
		} \
		else { \
			*totalLibMemory += ((nElements) + (8 - ((nElements) % 8))); \
		} \
    } \
    if (*(memoryMapIndex) >= MAX_NUM_PTR) { \
        return EB_ErrorInsufficientResources; \
    } \
    libMallocCount++;

**Comment by tianjunwork** [comment] 2019-10-15 20:41
Thank you @jsunintel Jing explaining how memory is managed inside SVT.
Hi @rexvl, spsPpsVps_buffer doesn't need to be freed after calling EbH265EncStreamHeader().
All the tracked allocation will be freed during DeInitEncoder().

If you checkout to 1.3 release, there is a SimpleApp with EbSimpleAppContext.c to show the usage of EbH265EncStreamHeader().

**Closed** 2019-10-21 20:35 UTC
Labels: invalid
